from math import*
totaldog=set(range(83))
totalcat=set(range(101))
totalfish=set(range(22))
dog_cat_fish=set(range(1,7))
other_product=set(range(1,35))
dog_cat=set(range(1,26))
dog_fish=set(range(1,3))
cat_fish=set(range(1,5))
only_dog=len(totaldog)-len(dog_fish)-len(dog_cat_fish)-len(dog_cat)
only_cat=len(totalcat)-len(dog_cat)-len(cat_fish)-len(dog_cat_fish)
only_fish=len(totalfish)-len(dog_fish)-len(cat_fish)-len(dog_cat_fish)
print(only_dog,"purchase were there for only dog product")
print(only_cat,"purchase were there for only cat product")
print(len(totaldog)+len(cat_fish)+only_fish,"purchase were for dog or fish poduct")
print(only_dog+only_cat+only_fish+len(dog_cat)+len(dog_fish)+len(cat_fish)+len(dog_cat_fish)+len(other_product),"were total purchase")
